### ISSUE TITLE
As a user I can make it possible for another user to complete tasks within a certain task tracker so that we can collaborate on things like household chores

### ISSUE THREAD

**Issue by Adhalianna** [Adhalianna/tracke.rs#35]
**Acceptance criteria**:

- [ ] Trackers must have a field listing all users (by email) who can add and modify tasks within a given tracker.
- [ ] A user who has been granted collaboration rights to a specific tracker by another user can view the tracker and tasks within it. This user cannot however modify the tracker, they can only modify tasks within the tracker. 
- [ ] To grant access to a tracker to another user, the owner only has to add the email of that user to the list of users with access to the tracker.
- [ ] The owner of the tracker is not mentioned on the list of users who were granted the access.
- [ ] When a user who does not own a tracker but has access to it fetches the tracker the email of the owner should be included in the fields of the response. 
- [ ] When a user attempts to access a tracker to which they do not have an access an error should be returned with status code 403 ("Forbidden") and a message "no access to the selected tracker". The same error should be returned when the user attempts to fetch a single task belonging to a tracker to which there is no access.
